import "../styles/globals.css";

export const metadata = {
  title: "Todo-app",
  description: "Generated by Next.js",
  icons: {
    icon: "/caixa-de-selecao.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
